site_name: 'example-docs'

nav:
  - Home: index.md

docs_dir: docs/audio-playback/sections

plugins:
  - techdocs-core
  - kroki
  - include-markdown
  - pdf-export:
      combined: true
  - mermaid2
