apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: audio-playback
  description: Audio playback system
  annotations:
    backstage.io/techdocs-ref: dir:../docs/audio-playback
spec:
  owner: team-c
  domain: playback
